namespace Matrix;

/// <summary>
/// One row of a feature report: either a measured scenario or a deployment capability.
/// </summary>
/// <remarks>
/// <paramref name="IsDeployment"/> is the discriminator. A scenario is contiguous from 1 in its
/// own <paramref name="Order"/> sequence and is measured; a deployment capability, such as Native
/// AOT compatibility, is a property of a build instead: it is validated rather than measured, it
/// never reaches a benchmark report, and so it can never enter the rating. It has its own
/// <paramref name="Order"/> sequence, independent of scenario order, because the two are never
/// compared to each other — only sorted within their own kind and shown as two separate groups.
/// </remarks>
public sealed record FeatureReportEntry(
    int Order,
    string Id,
    string Name,
    IReadOnlyList<FeatureResult> Results,
    bool IsDeployment = false)
{
    /// <summary>
    /// A report written before this field existed has no <c>IsDeployment</c> property, so
    /// deserializing it leaves the constructor argument at its default (<see langword="false"/>).
    /// The one report on disk with that shape today used the old <c>Order &gt;= 1000</c>
    /// convention this field replaces, so an absent value falls back to it here rather than
    /// misreading a deployment capability as a scenario until every report is regenerated by
    /// <c>aot-probes</c>. Once regenerated, every report states <c>IsDeployment</c> explicitly and
    /// this fallback never triggers.
    /// </summary>
    private const int LegacyDeploymentOrder = 1000;

    public bool IsDeployment { get; init; } = IsDeployment || Order >= LegacyDeploymentOrder;
}
